### ISSUE TITLE
[core] inconsistent builds - version requirement not met

### ISSUE THREAD

**Issue by jack1902** [airbnb/streamalert#1098]
TL;DR - `ERROR: astroid 2.3.2 has requirement six==1.12, but you'll have six 1.14.0 which is incompatible.`

Are you on the latest version of StreamAlert?

### Description
When running `./manage.py deploy -f ...` i get inconsistent dependencies with the error message:
`ERROR: astroid 2.3.2 has requirement six==1.12, but you'll have six 1.14.0 which is incompatible.`

### Steps to Reproduce

- `./manage.py init` or `./manage.py deploy -f ANY`

## Desired Change

Versions are pinned appropriately

**Comment by ryandeivert** [comment]
This actually isn't a bug - the reason this happens is because you are already within a `virtualenv` when we run the deployment stuff.. which itself does `pip install ... ` BUT this does a targeted install to a temporary directory. Pip is not smart enough to differentiate between your current venv and the target, and thus "warns" you that there are "conflicts" when in fact there are not.

You can test this by picking a function that this happens for and installing the pinned dependencies directly for that. Tip: print out the value of `pip_command` before this line: https://github.com/airbnb/streamalert/blob/d0e28f330a8636b9e080540ba098500801a857dc/streamalert_cli/manage_lambda/package.py#L184 with:

`print(' '.join(pip_command))`

**Comment by ryandeivert** [comment]
That said - I do still think we should address this, I just didn't get the time to figure out how or what was causing the conflict. Open to ideas. If you're troubleshooting, `pipdeptree` is a handy utility (installable via `pip install pipdeptree`) that will show you all dependencies for installed libs

**Comment by ryandeivert** [comment]
one way to solve this is to add `--no-warn-conflicts` to this:

https://github.com/airbnb/streamalert/blob/d0e28f330a8636b9e080540ba098500801a857dc/streamalert_cli/manage_lambda/package.py#L181

but I'm not sure I want to do this. will continue thinking

**Comment by ryandeivert** [comment]
Closing because the message printed by pip is just misleading and is incorrect. Pip has since been updated and the new version will actually print a more appropriate message.
