### ISSUE TITLE
Discussion: why not use Firehose Lambda transformation?

### ISSUE THREAD

**Issue by mazzy89** [airbnb/streamalert#295]
The project uses a different Kinesis stream from the Firehose delivery stream to collect events and detect events. Any reason why at the moment of design you didn't use the feature provided from Firehose which allow to attach a Lambda function to Firehose and transform the incoming events? In this way you avoid to create A Firehose delivery stream and a Kinesis stream.

**Comment by mime-frame** [comment]
Hey @mazzy89 

Thanks for the question! To answer this requires a bit of backstory :)

- The initial idea was that the Kinesis Stream would do realtime processing (via Lambda) and the Kinesis Firehose would be used for a persistent store. As a result, all "sources" were required to send to both the stream (for analysis) and the firehose (for storage, and eventually historically searching via Athena)
- As time has progressed, and as AWS has shipped additional features, we've realized this wasn't the vest idea and now we're going to have the existing Kinesis Stream (via Lambda) send to a Firehose, instead of requiring each "source" to send to both. 
- We're not using http://docs.aws.amazon.com/firehose/latest/dev/data-transformation.html because it's limited in the blueprints it provides and doesn't support formats like parquet or orc. 
- Net net, users will be able to send incoming data to whatever defined Firehose's they have, giving them the ability to segment or optimize how the data is stored.

Let me know if this makes sense
